# Generated by Django 5.1.4 on 2025-01-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_home', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
